[project]
name = "customers-churn-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "scikit-learn>=1.7.1",
    "sqlalchemy>=2.0.42",
    "uvicorn>=0.35.0",
]
